server:
  port: ${SERVER_PORT:8090}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000
            response-timeout: 8s
platform:
  security:
    issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8180/realms/ecommerce-local}
    jwk-set-uri: ${OIDC_JWK_SET_URI:http://localhost:8180/realms/ecommerce-local/protocol/openid-connect/certs}
    audience: api-gateway
  gateway:
    rate-limit:
      enabled: true
      requests-per-minute: 600
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
